[toolchain]
configure_args = --with-dpdk=/home/hkadayam/.conan2/p/dpdk94d4a462035a9/p --without-vhost --without-virtio --with-fio=/home/hkadayam/.conan2/p/fio4d606b6f46c3c/p/include/fio --with-uring=/home/hkadayam/.conan2/p/b/libura0ac657ce7567/p/include --without-isal --disable-tests --disable-unit-tests --prefix=/ --enable-debug
make_args = 
autoreconf_args = --force --install

