name: Build Commit

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      build-type:
        required: true
        type: string
      malloc-impl:
        required: true
        type: string
      prerelease:
        required: true
        type: string
      tooling:
        required: true
        type: string
      testing:
        required: true
        type: string
      deps-only:
        required: true
        type: string
jobs:
  SislBuild:
    uses: hkadayam/sisl/.github/workflows/build_dependencies.yml@master
    with:
      branch: master
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
      tooling: None
      testing: 'False'
      deps-only: 'True'

  IOMgrPRBuild:
    needs: SislBuild
    uses: ./.github/workflows/build_dependencies.yml
    with:
      branch: ${{ github.ref }}
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
      tooling: ${{ inputs.tooling }}
      testing: 'True'
      deps-only: 'False'
    if: ${{ github.event_name == 'pull_request' }}

  IOMgrCommitBuild:
    needs: SislBuild
    uses: ./.github/workflows/build_dependencies.yml
    with:
      branch: ${{ github.ref }}
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
      tooling: ${{ inputs.tooling }}
      testing: 'False'
      deps-only: 'False'
    if: ${{ github.event_name != 'pull_request' }}